import fs from "fs";

const files = [
  "src/lib/generatePhotovoltaiquePDF.ts",
  "src/lib/generateAgricolePDF.ts",
  "src/lib/generateIndustrielPDF.ts",
  "src/lib/generateOuvragesArtPDF.ts",
  "src/lib/generateRSEPDF.ts",
];

// Simple word-level replacements (unaccented -> accented)
const map = {
  "metalliques": "métalliques", "metallique": "métallique",
  "Metalliques": "Métalliques", "Metallique": "Métallique",
  "Photovoltaiques": "Photovoltaïques", "photovoltaiques": "photovoltaïques",
  "photovoltaique": "photovoltaïque",
  "Ombrieres": "Ombrières", "ombrieres": "ombrières", "ombriere": "ombrière",
  "Cle en main": "Clé en main", "cle en main": "clé en main",
  "installee": "installée", "installees": "installées", "installes": "installés",
  "Delais": "Délais", "delais": "délais",
  "respectes": "respectés", "respectees": "respectées",
  "concoit": "conçoit", "concoivent": "conçoivent",
  "Conformite": "Conformité", "conformite": "conformité",
  "europeennes": "européennes", "europeenne": "européenne",
  "Declarations": "Déclarations", "declarations": "déclarations",
  "certifiee": "certifiée", "certifiees": "certifiées",
  "certifie ": "certifié ", "Certifie ": "Certifié ",
  "Tracabilite": "Traçabilité", "tracabilite": "traçabilité",
  "qualifiees": "qualifiées", "qualifies": "qualifiés",
  "specialisees": "spécialisées",
  "Etude ": "Étude ", "etude ": "étude ",
  "faisabilite": "faisabilité",
  "ingenierie": "ingénierie", "ingenieurs": "ingénieurs", "Ingenieur": "Ingénieur",
  "reglementaire": "réglementaire", "reglementaires": "réglementaires",
  "reglementations": "réglementations",
  "modelisation": "modélisation", "Modelisation": "Modélisation",
  "decoupe": "découpe", "Decoupe": "Découpe",
  "robotise": "robotisé", "robotisee": "robotisée",
  "Controle": "Contrôle", "controle": "contrôle",
  "controles": "contrôles", "Controles": "Contrôles",
  "cablage": "câblage",
  "reseau": "réseau",
  "electriques": "électriques", "electrique": "électrique", "electricite": "électricité",
  "energetique": "énergétique", "Energetique": "Énergétique",
  "energie": "énergie", "Energie": "Énergie", "energies": "énergies",
  "preventifs": "préventifs",
  "degrades": "dégradés",
  "Equipement": "Équipement", "equipement": "équipement", "equipements": "équipements",
  "Benefices": "Bénéfices", "beneficie": "bénéficie",
  "severes": "sévères",
  "adaptee": "adaptée", "adaptees": "adaptées",
  "complementaire": "complémentaire",
  "reduite": "réduite",
  "reduction": "réduction", "Reduction": "Réduction",
  "materiaux": "matériaux", "Materiaux": "Matériaux", "matieres": "matières",
  "evolutifs": "évolutifs",
  "intermediaires": "intermédiaires",
  "flexibilite": "flexibilité",
  "amenagement": "aménagement",
  "activite": "activité",
  "liberte": "liberté", "rapidite": "rapidité",
  "pensee": "pensée",
  "methode": "méthode", "Methode": "Méthode",
  "budgetaire": "budgétaire",
  "planifiee": "planifiée",
  "livres": "livrés", "livree": "livrée",
  "Batiments": "Bâtiments", "batiments": "bâtiments",
  "Batiment": "Bâtiment", "batiment": "bâtiment",
  "entrepots": "entrepôts", "Entrepots": "Entrepôts",
  "cereales": "céréales",
  "elevage": "élevage", "Elevage": "Élevage",
  "Genie": "Génie", "genie": "génie",
  "portees": "portées", "portee": "portée", "Portee": "Portée",
  "pietonnes": "piétonnes",
  "ferrees": "ferrées",
  "geometries": "géométries", "geometrie": "géométrie",
  "extremes": "extrêmes",
  "resistance": "résistance", "Resistance": "Résistance",
  "durabilite": "durabilité", "duree": "durée",
  "Rehabilitation": "Réhabilitation",
  "remise en etat": "remise en état",
  "etats ": "états ", "etat ": "état ",
  "reguliers": "réguliers",
  "responsabilite": "responsabilité", "Responsabilite": "Responsabilité",
  "securite": "sécurité", "Securite": "Sécurité",
  "epanouissement": "épanouissement",
  "egalite": "égalité",
  "Diversite": "Diversité",
  "feminisation": "féminisation",
  "demarche": "démarche",
  "ecosystemes": "écosystèmes",
  "dechets": "déchets", "dechet": "déchet",
  "recyclables": "recyclables",
  "integre ": "intégré ", "integrees": "intégrées",
  "resultats": "résultats",
  "determines": "déterminés",
  "Mickael": "Mickaël",
  "strategie": "stratégie",
  "creation": "création",
  "procedes": "procédés",
  "premieres": "premières", "premiere": "première",
  "residuelles": "résiduelles",
  "reintegrees": "réintégrées",
  "numerique": "numérique",
  "eolien": "éolien",
  "groupee": "groupée",
  "engages": "engagés",
  "kilometres": "kilomètres",
  "necessaire": "nécessaire",
  "economise": "économisé",
  "neutralite": "neutralité", "Neutralite": "Neutralité",
  "decarbonation": "décarbonation",
  "developpement": "développement",
  "amelioration": "amélioration",
  "delivrees": "délivrées",
  "systematiques": "systématiques", "systematiquement": "systématiquement",
  "generations": "générations",
  "superieur": "supérieur", "inferieur": "inférieur",
  "Deploiement": "Déploiement",
  "biodiversite": "biodiversité",
  "metier": "métier",
  "dedie": "dédié",
  "frequence": "fréquence",
  "evitees": "évitées",
  "equipent": "équipent",
  "Capacite": "Capacité", "capacite": "capacité",
  "eloignes": "éloignés",
  "personnalisee": "personnalisée",
  "etapes": "étapes", "etape": "étape",
  "compactees": "compactées", "triees": "triées",
  "recuperees": "récupérées",
  "pieces": "pièces", "piece": "pièce",
  "magnetoscopie": "magnétoscopie",
  "seisme": "séisme",
  "decennale": "décennale",
  "renovation": "rénovation", "Renovation": "Rénovation",
  "Eco-conception": "Éco-conception",
  "paysagere": "paysagère",
  "executees": "exécutées",
  "executes": "exécutés",
  "execution": "exécution",
  "referent": "référent",
  "interesse": "intéressé",
  "Puissance installee": "Puissance installée",
  "Capacite / an": "Capacité / an",
  "d'execution": "d'exécution",
  "Classe d'exec.": "Classe d'exéc.",
  "nuances d'acier": "nuances d'acier",
};

let totalChanges = 0;
for (const file of files) {
  let content = fs.readFileSync(file, "utf8");
  let changes = 0;
  // Sort by length descending to replace longer phrases first
  const sorted = Object.entries(map).sort((a, b) => b[0].length - a[0].length);
  for (const [from, to] of sorted) {
    const escaped = from.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
    const regex = new RegExp(escaped, "g");
    const before = content;
    content = content.replace(regex, to);
    if (content !== before) changes++;
  }
  if (changes > 0) {
    fs.writeFileSync(file, content, "utf8");
    totalChanges += changes;
  }
  console.log(`${file}: ${changes} patterns applied`);
}
console.log(`\nTotal: ${totalChanges} patterns applied`);
